// This file is auto-generated by `php artisan stimulus:install`
// Run that command whenever you add a new controller or create them with
// `php artisan stimulus:make controllerName`

import { Stimulus } from '../libs/stimulus'


import FlashController from './flash_controller'
Stimulus.register('flash', FlashController)

import HelloController from './hello_controller'
Stimulus.register('hello', HelloController)

import TextareaAutogrowController from './textarea_autogrow_controller'
Stimulus.register('textarea-autogrow', TextareaAutogrowController)